1. Read the dataset using pandas.

In [1]:
import pandas as pd
df=pd.read_csv('tags.csv')
df.head()

   userId  movieId                         tag      timestamp
0  144473      933                 hw classics  1169455118000
1  144473      933            alfred hitchcock  1169455125000
2  144473    49272             guilty pleasure  1169457148000
3  144473     8228  not available from netflix  1169457152000
4  144473     7925            in netflix queue  1169457154000

2. Extract the first row from tags and print its type.

In [2]:
f_row=df.iloc[0,:]
print(f_row)
print(type(f_row))

userId              144473
movieId                933
tag            hw classics
timestamp    1169455118000
Name: 0, dtype: object
<class 'pandas.core.series.Series'>

3. Extract row 0, 11, 2000 from tags DataFrame.

In [3]:
r_0=df.iloc[0,:]
print(r_0)
r_11=df.iloc[11,:]
print(r_11)
r_2000=df.iloc[2000,:]
print(r_2000)

userId              144473
movieId                933
tag            hw classics
timestamp    1169455118000
Name: 0, dtype: object
userId                          145789
movieId                          40955
tag          gender identity confusion
timestamp                1169463159000
Name: 11, dtype: object
userId              145552
movieId                527
tag                history
timestamp    1169718618000
Name: 2000, dtype: object

4. Print index, columns of the DataFrame.

In [4]:
df.index

RangeIndex(start=0, stop=628157, step=1)

5. Calculate descriptive statistics for the 'ratings' column of the
ratings DataFrame. Verify using describe().

In [6]:
df_ratings=pd.read_csv('ratings.csv')
v_ratings=df_ratings.iloc[:,2]
print(v_ratings.sum())
print(v_ratings.mean())
print(v_ratings.max())
print(v_ratings.min())
print(v_ratings.count())
print(df_ratings.describe())

97982013.5
3.5304452124932677
5.0
0.5
27753444
             userId       movieId        rating     timestamp
count  2.775344e+07  2.775344e+07  2.775344e+07  2.775344e+07
mean   1.419420e+05  1.848800e+04  3.530445e+00  1.193122e+09
std    8.170740e+04  3.510263e+04  1.066353e+00  2.160482e+08
min    1.000000e+00  1.000000e+00  5.000000e-01  7.896520e+08
25%    7.117600e+04  1.097000e+03  3.000000e+00  9.986053e+08
50%    1.420220e+05  2.716000e+03  3.500000e+00  1.174256e+09
75%    2.124590e+05  7.150000e+03  4.000000e+00  1.422744e+09
max    2.832280e+05  1.938860e+05  5.000000e+00  1.537945e+09

6. Filter out ratings with rating > 5

In [7]:
data_f=df_ratings[df_ratings['rating'] >= 5]
data_f['rating']

40          5.0
61          5.0
107         5.0
109         5.0
111         5.0
119         5.0
170         5.0
176         5.0
217         5.0
218         5.0
228         5.0
230         5.0
235         5.0
249         5.0
252         5.0
254         5.0
261         5.0
274         5.0
277         5.0
278         5.0
295         5.0
325         5.0
339         5.0
346         5.0
347         5.0
348         5.0
351         5.0
378         5.0
406         5.0
430         5.0
           ...
27753352    5.0
27753354    5.0
27753355    5.0
27753357    5.0
27753360    5.0
27753361    5.0
27753362    5.0
27753363    5.0
27753369    5.0
27753370    5.0
27753373    5.0
27753374    5.0
27753376    5.0
27753377    5.0
27753380    5.0
27753382    5.0
27753390    5.0
27753392    5.0
27753397    5.0
27753398    5.0
27753401    5.0
27753407    5.0
27753415    5.0
27753419    5.0
27753422    5.0
27753429    5.0
27753431    5.0
27753436    5.0
27753437    5.0
27753438    5.0
Name: rating, Length: 4071135, dtype: float64

7. Find how many null values, missing values are present. Deal with them. Print out how many rows have been modified.

In [8]:
df_movies=pd.read_csv('movies.csv')
print("Null Values  handled in movies {}".format(df_movies.isnull().count().sum()))
print("Null Values handled in tags {}".format(df.isnull().count().sum()))
print("Null Values handled  in ratings {}".format(df_ratings.isnull().count().sum()))
df_movies.drop(df_movies.isnull().index,inplace=True)
df.drop(df.isnull().index,inplace=True)
df_ratings.drop(df_ratings.isnull().index,inplace=True)
print("Null Values  in movies {}".format(df_movies.isnull().count().sum()))
print("Null Values  in tags {}".format(df.isnull().count().sum()))
print("Null Values   in ratings {}".format(df_ratings.isnull().count().sum()))

Null Values  handled in movies 174294
Null Values handled in tags 2512628
Null Values handled  in ratings 111013776
Null Values  in movies 0
Null Values  in tags 0
Null Values   in ratings 0

 8. Filter out movies from the movies DataFrame that are of type 'Animation'.

In [9]:
df_movies=pd.read_csv('movies.csv')
df_movies.head(11)
movies=df_movies['genres'].str.contains('Animation')
type(movies)
df_movies[movies]

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
12,13,Balto (1995),Adventure|Animation|Children
47,48,Pocahontas (1995),Animation|Children|Drama|Musical|Romance
236,239,"Goofy Movie, A (1995)",Animation|Children|Comedy|Romance
241,244,Gumby: The Movie (1995),Animation|Children
310,313,"Swan Princess, The (1994)",Animation|Children
360,364,"Lion King, The (1994)",Adventure|Animation|Children|Drama|Musical|IMAX
388,392,"Secret Adventures of Tom Thumb, The (1993)",Adventure|Animation
547,551,"Nightmare Before Christmas, The (1993)",Animation|Children|Fantasy|Musical
553,558,"Pagemaster, The (1994)",Action|Adventure|Animation|Children|Fantasy
582,588,Aladdin (1992),Adventure|Animation|Children|Comedy|Musical
588,594,Snow White and the Seven Dwarfs (1937),Animation|Children|Drama|Fantasy|Musical
589,595,Beauty and the Beast (1991),Animation|Children|Fantasy|Musical|Romance|IMAX
590,596,Pinocchio (1940),Animation|Children|Fantasy|Musical
604,610,Heavy Metal (1981),Action|Adventure|Animation|Horror|Sci-Fi
610,616,"Aristocats, The (1970)",Animation|Children
624,631,All Dogs Go to Heaven 2 (1996),Adventure|Animation|Children|Fantasy|Musical|R...
653,661,James and the Giant Peach (1996),Adventure|Animation|Children|Fantasy|Musical
664,673,Space Jam (1996),Adventure|Animation|Children|Comedy|Fantasy|Sc...
697,709,Oliver & Company (1988),Adventure|Animation|Children|Comedy|Musical
708,720,Wallace & Gromit: The Best of Aardman Animatio...,Adventure|Animation|Comedy
728,741,Ghost in the Shell (Kôkaku kidôtai) (1995),Animation|Sci-Fi
732,745,Wallace & Gromit: A Close Shave (1995),Animation|Children|Comedy
770,783,"Hunchback of Notre Dame, The (1996)",Animation|Children|Drama|Musical|Romance
871,888,Land Before Time III: The Time of the Great Gi...,Adventure|Animation|Children|Musical
1003,1022,Cinderella (1950),Animation|Children|Fantasy|Musical|Romance
1004,1023,Winnie the Pooh and the Blustery Day (1968),Animation|Children|Musical
1005,1024,"Three Caballeros, The (1945)",Animation|Children|Musical
1006,1025,"Sword in the Stone, The (1963)",Animation|Children|Fantasy|Musical
1010,1029,Dumbo (1941),Animation|Children|Drama|Musical
...,...,...,...
57813,193217,Foul Hunting (1947),Animation|Comedy
57823,193243,Next Gen (2018),Action|Adventure|Animation
57849,193297,Scooby-Doo! and the Gourmet Ghost (2018),Adventure|Animation|Crime
57858,193329,Grandfather and grandson (1950),Animation
57859,193331,Последняя невеста Змея Горыныча (1978),Animation|Fantasy
57870,193357,Gnomes (1981),Animation|Children|Fantasy
57875,193369,Starie znakomie (1956),Animation
57892,193411,Как один мужик двух генералов прокормил (1965),Animation
57935,193517,The Magic Treasure (1950),Animation|Children
57943,193535,Brothers Liu (1953),Animation|Children
57944,193537,The Little Mermaid (1968),Animation|Fantasy
57956,193565,Gintama: The Movie (2010),Action|Animation|Comedy|Sci-Fi
57957,193567,anohana: The Flower We Saw That Day - The Movi...,Animation|Drama
57958,193569,Enchanted Princess (2018),Animation|Children|Fantasy
57960,193573,Love Live! The School Idol Movie (2015),Animation
57963,193581,Black Butler: Book of the Atlantic (2017),Action|Animation|Comedy|Fantasy
57964,193583,No Game No Life: Zero (2017),Animation|Comedy|Fantasy
57966,193587,Bungo Stray Dogs: Dead Apple (2018),Action|Animation
57978,193617,Nelly & Simon: Mission Yeti (2018),Adventure|Animation|Children
57986,193639,The Winter's Tale (1981),Animation
57991,193653,Большой Ух (1989),Animation|Children
57992,193655,Barmaley (1941),Animation
58006,193687,Когда зажигаются ёлки (1950),Animation
58018,193721,Терем-теремок (1971),Animation
58034,193753,Uncle Ow (1979),Animation
58046,193777,Almost Home (2014),Adventure|Animation|Sci-Fi
58056,193799,Lupin the Third: Daisuke Jigen's Gravestone (2...,Action|Adventure|Animation|Comedy
58057,193801,Lupin the Third: The Blood Spray of Goemon Ish...,Action|Animation|Crime
58058,193803,Bleach: Memories of Nobody (2006),Animation|Fantasy|Sci-Fi
58074,193837,Lily C.A.T. (1987),Animation|Horror|Sci-Fi

 9. Find the average rating of movies

In [10]:
df_ratings=pd.read_csv('ratings.csv')
print("Average rating of movies is : {}".format(df_ratings['rating'].mean()))

Average rating of movies is : 3.5304452124932677

 12. Split 'genres' into multiple columns

In [19]:
df_movies.head(10)
df_movies.pivot(index='movieId',columns='genres',values='title')

genres,(no genres listed),Action,Action|Adventure,Action|Adventure|Animation,Action|Adventure|Animation|Children,Action|Adventure|Animation|Children|Comedy,Action|Adventure|Animation|Children|Comedy|Fantasy,Action|Adventure|Animation|Children|Comedy|IMAX,Action|Adventure|Animation|Children|Comedy|Romance,Action|Adventure|Animation|Children|Comedy|Sci-Fi,...,Sci-Fi|Thriller|War,Sci-Fi|Thriller|Western,Sci-Fi|War,Sci-Fi|Western,Thriller,Thriller|War,Thriller|Western,War,War|Western,Western
movieId,,,,,,,,,,,,,,,,,,,,,
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,Sudden Death (1995),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193823,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
193825,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
193827,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
193829,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
193833,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
193835,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
193837,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
193839,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
193841,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
193843,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
193845,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Dywizjon 303 (2018),NaN,NaN
193849,Rafinha Bastos: Ultimatum (2018),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
193851,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
193853,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
193855,"Spring Night, Summer Night (1967)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
193857,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
193859,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
193861,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
193863,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
193864,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
193866,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
193868,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
193870,Isabelle Eberhardt (1991),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
193872,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
193874,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
193876,The Great Glinka (1946),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
193878,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
193880,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
193882,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
193886,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

13. Extract year from title e.g. (1995).

In [20]:
df_movies.head(10)

a=df_movies['title'].str.extract("(\((.*)\))")[0]
a=df_movies['title'].str.extract("(\(([0-9]*)\))")[0]
a.head(10)

0    (1995)
1    (1995)
2    (1995)
3    (1995)
4    (1995)
5    (1995)
6    (1995)
7    (1995)
8    (1995)
9    (1995)
Name: 0, dtype: object